using System;
using System.Linq;
using TCG.Foundation;
using TCG.Table;
using UnityEngine;
public static class AuthorCardChecks
{
    static int checks,id=40000;static ContentCatalog catalog;static EffectRegistry registry=new EffectRegistry();
    static void Check(bool ok,string label){checks++;if(!ok)throw new Exception("AUTHOR CARDS: "+label);}
    static void Do(Match m,ActionKind kind,int target=-1,int unit=-1,string card=null,int[] units=null,int[] blockers=null){if(!m.Try(new Command{player=m.Controller,revision=m.Revision,kind=kind,target=target,unit=unit,card=card,pile=0,units=units??Array.Empty<int>(),blockers=blockers??Array.Empty<int>()},out var error))throw new Exception("AUTHOR "+kind+": "+error);}
    static void Settle(Match m){for(int guard=0;guard<200&&!m.Over;guard++){if(m.Choice!=null){Do(m,ActionKind.Choose,m.Choice.Options.FirstOrDefault(x=>x.Key>=0)?.Key??m.Choice.Options[0].Key);}else if(m.Defense!=null){var defenders=m.Board[m.Defense.Target].Pieces.Where(p=>p.Owner==m.Defense.Defender).ToArray();Do(m,ActionKind.Defend,blockers:Enumerable.Repeat(defenders.Length>0?defenders[0].Id:-1,m.Defense.Attackers.Length).ToArray());}else if(m.Stack.Count>0)Do(m,ActionKind.Pass);else return;}Check(m.Over,"settle guard");}
    static Match Game(){var m=ContentLoader.TestTable(catalog,registry,2,false,5);Do(m,ActionKind.DrawMain);Do(m,ActionKind.Place,Match.Capital(m.Active,2));Do(m,ActionKind.NextPhase);foreach(var c in m.Board){c.Terrain=catalog.Get("test-land-0");c.Owner=m.Active;c.TerrainOwner=m.Active;}for(int n=0;n<7;n++)m.Seats[m.Active].mana[n]=100;return m;}
    static Piece Add(Match m,string card,int at,int owner=-1){var p=new Piece(id++,owner<0?m.Active:owner,catalog.Get(card)){Game=m};m.Board[at].pieces.Add(p);return p;}
    static void Cast(Match m,string card){m.Seats[m.Active].hand.Add(catalog.Get(card));Do(m,ActionKind.Play,card:card);Settle(m);}
    public static void Run()
    {
        checks=0;catalog=ContentLoader.Load(registry);
        {var m=Game();var p=Add(m,"MED-197",60);var victim=Add(m,"MED-085",61);int hand=m.Seats[m.Active].HandCount;Do(m,ActionKind.Activate,unit:p.Id);Settle(m);Check(m.Find(victim.Id)==null&&p.Attack==3&&p.Defense==6&&p.Actions==3&&m.Seats[m.Active].HandCount==hand+1,"ossuary sacrifice draw counters PA");}
        {var m=Game();var p=Add(m,"MED-200",60);Check(p.Range==3,"archer buffs own range");Add(m,"MED-085",61,1-m.Active);Check(p.Range==2,"adjacent enemy suppresses range");}
        {var m=Game();m.Board[60].Terrain=catalog.Get("MED-207");var p=Add(m,"MED-085",60);Check(p.Attack==3&&p.Defense==2,"reverse garden");}
        {var m=Game();m.Board[60].Terrain=catalog.Get("MED-208");m.Board[90].Terrain=catalog.Get("MED-208");var p=Add(m,"MED-085",60);Do(m,ActionKind.Move,90,p.Id);Check(m.Position(p.Id)==90&&p.Movement==1,"portal one movement unlimited range");}
        {var m=Game();m.Board[61].Terrain=catalog.Get("MED-206");var p=Add(m,"MED-085",60);Check(!m.CanMove(p.Id,61),"mountain blocks nonflying");}
        {var m=Game();m.Board[60].Terrain=catalog.Get("MED-212");var p=Add(m,"MED-085",60);int life=m.Seats[m.Active].Life;m.Deal(p,20);Settle(m);Check(m.Seats[m.Active].Life==life+1,"hungry forest heals");}
        {var m=Game();var p=Add(m,"MED-195",60);m.Deal(p,100);Settle(m);Check(Match.Neighbors(60).Concat(new[]{60}).All(n=>m.Board[n].Terrain.Name=="Floresta básica"),"aberration transforms neighbors");}
        {var m=Game();var p=Add(m,"MED-213",61);var g=Add(m,"MED-194",60);Do(m,ActionKind.Move,61,g.Id);Settle(m);Check(g.Attack==3,"warehouse permanent attack");}
        {var m=Game();Add(m,"MED-222",60);var p=Add(m,"MED-085",61);int mana=m.Seats[m.Active].Mana.Sum();Do(m,ActionKind.Activate,unit:m.Board[60].Pieces[0].Id);Settle(m);Check(m.Board[61].Pieces.Count==2&&m.Board[61].Pieces.Count(x=>x.Token)==1&&m.Seats[m.Active].Mana.Sum()==mana-2,"mirror token copy and cost");Do(m,ActionKind.NextPhase);Do(m,ActionKind.Pass);Do(m,ActionKind.Pass);Check(m.Board[61].Pieces.All(x=>!x.Token),"copy disappears at end");}
        {var m=Game();var commander=catalog.Get("MED-200");m.Seats[m.Active].Commander=commander;m.Seats[m.Active].CommanderReady=true;int home=Match.Capital(m.Active,2);int mana=m.Seats[m.Active].Mana.Sum();Do(m,ActionKind.SummonCommander,home);Settle(m);var p=m.Board[home].Pieces.Single();Check(p.CommandUnit&&m.Seats[m.Active].CommanderCasts==1&&m.Seats[m.Active].Mana.Sum()==mana-6,"commander first cost and flag");m.Deal(p,99);Do(m,ActionKind.NextPhase);Settle(m);Check(m.Seats[p.Owner].CommanderReady,"commander returns to zone");}
        {var m=Game();var p=Add(m,"MED-085",60);var substitute=Add(m,"MED-085",61);m.Seats[m.Active].hand.Clear();m.Seats[m.Active].hand.Add(catalog.Get("MED-220"));m.Deal(p,99);Do(m,ActionKind.NextPhase);Check(m.Choice!=null,"death response window offered");Settle(m);Check(m.Find(p.Id)!=null&&p.Health>0&&m.Find(substitute.Id)==null&&!m.Seats[p.Owner].hand.Contains(catalog.Get("MED-220")),"destiny played only at death substitutes victim");}
        {var m=Game();var p=Add(m,"MED-224",60);var host=Add(m,"MED-085",60);Do(m,ActionKind.Equip,host.Id,p.Id);Check(host.Attack==4,"parasite equipment attack");}
        {var m=Game();var cat=Add(m,"MED-215",60);var victim=Add(m,"MED-085",61);var target=Add(m,"MED-085",62,1-m.Active);Do(m,ActionKind.Activate,unit:cat.Id);Settle(m);Check(m.Find(victim.Id)==null,"catapult sacrifices");}
        {var m=Game();var c=catalog.Get("MED-200");m.Seats[m.Active].Commander=c;m.Seats[m.Active].CommanderReady=true;m.Seats[m.Active].CommanderCasts=1;int mana=m.Seats[m.Active].Mana.Sum();Do(m,ActionKind.SummonCommander,Match.Capital(m.Active,2));Settle(m);Check(m.Seats[m.Active].Mana.Sum()==mana-8,"commander recast adds two generic");}
        {var m=Game();int enemy=1-m.Active,capital=Match.Capital(enemy,2);var p=Add(m,"MED-200",capital+(capital%11==0?1:-1));p.CommandUnit=true;p.Modifiers.Add(new Modifier{Attack=23});Do(m,ActionKind.Attack,capital,units:new[]{p.Id});Do(m,ActionKind.Defend,blockers:new[]{-1});Settle(m);Check(m.CommanderDamage(p.Owner,enemy)==25&&!m.Seats[enemy].Eliminated,"25 commander damage not lethal");p.Modifiers.Clear();p.Movement=2;p.Actions=2;Do(m,ActionKind.Attack,capital,units:new[]{p.Id});Do(m,ActionKind.Defend,blockers:new[]{-1});Settle(m);Check(m.Seats[enemy].Eliminated&&m.CommanderDamage(p.Owner,enemy)>=26,"26 threshold accumulated");}
        {var m=Game();var master=Add(m,"MED-196",59);var a=Add(m,"MED-085",60);var b=Add(m,"MED-085",72);var enemy=Add(m,"MED-199",61,1-m.Active);Do(m,ActionKind.Attack,61,units:new[]{a.Id,b.Id});Do(m,ActionKind.Defend,blockers:new[]{enemy.Id,enemy.Id});Settle(m);Check(a.Attack==6&&b.Attack==6,"spears counts two origins and permanent bonus");}
        {var m=Game();var khan=Add(m,"MED-201",59);var a=Add(m,"MED-085",60);Do(m,ActionKind.Move,61,a.Id);var enemy=Add(m,"MED-199",62,1-m.Active);enemy.Modifiers.Add(new Modifier{Attack=-3});Do(m,ActionKind.Attack,62,units:new[]{a.Id});Do(m,ActionKind.Defend,blockers:new[]{enemy.Id});Settle(m);Check(enemy.Damage==3,"khan movement increases first hit");Check(a.Attack==2,"khan bonus ends after combat");}
        {var m=Game();m.Board[60].Terrain=catalog.Get("MED-210");var a=Add(m,"MED-085",60);var enemy=Add(m,"MED-199",61,1-m.Active);enemy.Modifiers.Add(new Modifier{Attack=-3});Do(m,ActionKind.Attack,61,units:new[]{a.Id});Do(m,ActionKind.Defend,blockers:new[]{enemy.Id});Settle(m);Check(enemy.Damage==4,"arena attack bonus");Check(a.Attack==2,"arena bonus combat only");}
        {var m=Game();var grave=Add(m,"MED-216",60);var victim=Add(m,"MED-085",61);m.Deal(victim,50);m.ResolveInitialEffects();Settle(m);Check(!m.Seats[m.Active].grave.Contains(victim.Card),"mausoleum replaces grave");Do(m,ActionKind.Activate,unit:grave.Id);Settle(m);Check(m.Find(grave.Id)==null&&m.Seats[m.Active].hand.Contains(victim.Card),"mausoleum releases and recovers");}
        {var m=Game();var cannon=Add(m,"MED-221",60);var gunner=Add(m,"MED-085",60);Do(m,ActionKind.Activate,unit:cannon.Id);Settle(m);Check(gunner.Actions==0&&gunner.Damage==2,"cannon two damage per PA");}
        {var m=Game();m.Board[61].Terrain=catalog.Get("MED-211");m.Board[60].Terrain=catalog.Get("MED-211");var p=Add(m,"MED-085",60);Do(m,ActionKind.Move,61,p.Id);Settle(m);Check(m.Position(p.Id)!=61&&m.Stack.Count==0,"bridge force move without chain");}
        {var m=Game();var lighthouse=Add(m,"MED-217",61);var p=Add(m,"MED-085",60);Cast(m,"MED-135");Check(m.Choice==null,"movement choices resolve with lighthouse");}
        {var m=Game();var goblin=Add(m,"MED-194",60);Do(m,ActionKind.Activate,unit:goblin.Id);Settle(m);Check(m.Board.SelectMany(b=>b.Pieces).Any(p=>p.Token&&p.Card.Subtypes.Contains("Goblin")),"goblin creates mission token");}
        {var m=Game();m.Board[60].Terrain=catalog.Get("MED-205");var p=Add(m,"MED-085",60);m.Deal(p,50);Settle(m);Check(m.Board.SelectMany(b=>b.Pieces).Any(q=>q.Token&&q.Card.Subtypes.Contains("Esqueleto")),"graveyard creates skeleton mission");}
        {var m=Game();var widow=Add(m,"MED-198",60);var own=Add(m,"MED-085",59);m.Deal(own,99);var enemy=Add(m,"MED-085",61,1-m.Active);m.Deal(enemy,99);Settle(m);Check(m.Seats[m.Active].main.Last()==own.Card,"widow recovers to top");}
        {var m=Game();var king=Add(m,"MED-202",59);var heir=Add(m,"MED-085",60);var victim=Add(m,"MED-085",61);m.Deal(victim,99);Settle(m);Check(heir.Attack==4,"martyrs inherits attack only");}
        {var m=Game();var before=m.Board.Select(c=>c.Terrain).ToArray();Cast(m,"MED-218");Check(m.Seats[m.Active].terrainGrave.Count>0,"terramorph replaces owned terrain");}
        {var m=Game();var p=Add(m,"MED-085",0);Cast(m,"MED-219");Check(m.Position(p.Id)==1,"teletransport carries occupant");Check(m.Board[Match.Capital(m.Active,2)].CapitalOwner==m.Active,"teletransport leaves capital");}        Debug.Log("AUTHOR CARD CHECKS PASSED: "+checks);
    }
}
