using System;
using System.Linq;
using TCG.Foundation;
using TCG.Table;
using UnityEngine;
public static class BicolorChecks
{
 static int checks,id=90000;static ContentCatalog catalog;static EffectRegistry registry=new EffectRegistry();
 static void Check(bool ok,string name){checks++;if(!ok)throw new Exception("BICOLOR: "+name);}
 static void Do(Match m,ActionKind k,int target=-1,int unit=-1,int[] units=null,int[] blockers=null){if(!m.Try(new Command{player=m.Controller,revision=m.Revision,kind=k,target=target,unit=unit,pile=0,units=units??Array.Empty<int>(),blockers=blockers??Array.Empty<int>()},out var e))throw new Exception("BICOLOR "+k+": "+e);}
 static void Settle(Match m){m.ResolveInitialEffects();for(int n=0;n<200&&!m.Over;n++){if(m.Choice!=null)Do(m,ActionKind.Choose,m.Choice.Options.First(x=>x.Key>=0).Key);else if(m.Defense!=null)Do(m,ActionKind.Defend,blockers:Enumerable.Repeat(m.Board[m.Defense.Target].Pieces.FirstOrDefault(p=>p.Owner==m.Defense.Defender)?.Id??-1,m.Defense.Attackers.Length).ToArray());else if(m.Stack.Count>0)Do(m,ActionKind.Pass);else return;}Check(m.Over,"settle bounded");}
 static Match Game(){var m=ContentLoader.TestTable(catalog,registry,2,false,5);Do(m,ActionKind.DrawMain);Do(m,ActionKind.Place,Match.Capital(m.Active,2));Do(m,ActionKind.NextPhase);foreach(var c in m.Board){c.Terrain=catalog.Get("test-land-0");c.Owner=m.Active;c.TerrainOwner=m.Active;}foreach(var s in m.Seats){s.hand.Clear();Array.Clear(s.mana,0,7);}return m;}
 static Piece Add(Match m,string card,int at,int owner=-1){var p=new Piece(id++,owner<0?m.Active:owner,catalog.Get(card)){Game=m};m.Board[at].pieces.Add(p);return p;}
 public static void Run(){checks=0;catalog=ContentLoader.Load(registry);
  {var f=new CardFilter();var elo=catalog.Get("MED-225");Check(f.Matches(elo,true),"empty filters");f.Colors.Add(0);Check(f.Matches(elo,true),"bicolor matches Sol");f.Colors.Clear();f.Colors.Add(1);Check(f.Matches(elo,true),"bicolor matches Lua");f.Colors.Add(3);Check(f.Matches(catalog.Get("MED-227"),true),"OR colors");f.Types.Add(CardType.Terrain);Check(!f.Matches(elo,true),"AND categories");f.Clear();f.OwnedOnly=true;Check(!f.Matches(elo,false),"owned only");f.Clear();f.Costs.Add(6);Check(f.Matches(elo,true),"6 plus cost");f.Clear();Check(f.Matches(elo,true,"MED-225"),"search id");Check(!f.Matches(elo,true,"not a card"),"search excluded");}
  {var m=Game();var elo=Add(m,"MED-225",60);Check(elo.Attack==3&&elo.Defense==3,"devotion counts self");var ally=Add(m,"MED-226",59);Check(elo.Attack==5&&elo.Defense==3,"devotion colored costs");Add(m,"MED-225",62,1-m.Active);Check(elo.Attack==5,"enemy excluded devotion");m.Deal(ally,99);Settle(m);Check(elo.Attack==3,"devotion after death");Check(elo.Card.PrintedStats=="X/Y","printed variables");}
  {var m=Game();var r=Add(m,"MED-230",60);var p=Add(m,"MED-085",59);Check(p.Actions==p.Card.Actions+1,"zero tie Lucio");m.Seats[m.Active].mana[3]=1;Check(p.Actions==p.Card.Actions,"fire suppress Lucio");m.Seats[m.Active].mana[5]=2;Check(p.Actions==p.Card.Actions+1,"terra activates Lucio");p.Actions--;m.Seats[m.Active].mana[3]=3;m.Seats[m.Active].mana[3]=0;Check(p.Actions==p.Card.Actions,"aura toggle no refill");var target=Add(m,"MED-229",61,1-m.Active);m.DamageTo(target,1,null,true,m.Active);Check(target.Damage==1,"terra no damage bonus");m.Seats[m.Active].mana[3]=2;m.DamageTo(target,1,null,true,m.Active);Check(target.Damage==4,"tie Dazmond");m.DamageTo(target,1,p,true,m.Active);Check(target.Damage==5,"creature damage excluded");}
  {var m=Game();var l=Add(m,"MED-226",59);var ally=Add(m,"MED-085",60);var enemy=Add(m,"MED-199",61,1-m.Active);Do(m,ActionKind.Attack,61,units:new[]{ally.Id});Do(m,ActionKind.Defend,blockers:new[]{enemy.Id});Settle(m);Check(m.Seats[l.Owner].DeathCounters==1,"combat death counter");var extra=Add(m,"MED-085",58);m.Deal(extra,99);Settle(m);Check(m.Seats[l.Owner].DeathCounters==1,"noncombat excluded");m.Seats[l.Owner].DeathCounters=10;int pa=l.Actions;Do(m,ActionKind.Activate,unit:l.Id);Settle(m);var copy=m.Board[Match.Capital(l.Owner,2)].Pieces.Single(p=>p.Token);Check(copy.Attack==1&&copy.Defense==1&&l.Actions==pa,"copy 1/1 no PA");Check(m.Seats[l.Owner].DeathCounters==10-ally.Card.TotalCost,"converted cost paid");Check(m.Seats[l.Owner].Graveyard.Contains(copy.Card),"copy leaves original");}
  {var m=Game();var inventor=Add(m,"MED-227",50);var own=Add(m,"MED-085",60);var target=Add(m,"MED-229",61,1-m.Active);m.Deal(own,99);Settle(m);Check(target.Damage==2,"inventor own death radius");var other=Add(m,"MED-085",62,1-m.Active);m.Deal(other,99);Settle(m);Check(target.Damage==2,"enemy death no trigger");}
  {var m=Game();var fish=Add(m,"MED-228",60);m.Seats[m.Active].main.Clear();m.Seats[m.Active].main.Add(catalog.Get("MED-193"));m.Seats[m.Active].LastCreatedTerrain=-1;Check(!m.CanActivate(fish.Id),"fisher requires created terrain");m.Seats[m.Active].LastCreatedTerrain=59;Do(m,ActionKind.Activate,unit:fish.Id);Settle(m);Check(fish.Actions==4&&m.Board[59].Pieces.Any(p=>p.Card.Id=="MED-193"),"fisher PA summon water");Check(fish.Card.ColoredCost[2]==1&&fish.Card.ColoredCost[1]==0,"fisher corrected water cost");}
  {var m=Game();int enemy=1-m.Active;var p=Add(m,"MED-085",60);var bear=Add(m,"MED-229",63,enemy);m.Board[61].Owner=enemy;int pa=bear.Actions,mv=bear.Movement;Do(m,ActionKind.Move,61,p.Id);Check(m.Position(p.Id)==60&&m.Position(bear.Id)==61,"bear interrupts invasion");Check(bear.Actions==pa&&bear.Movement==mv&&p.Movement==p.Card.Movement,"guard free no failed movement payment");Check(!m.CanMove(p.Id,61)&&m.CanAttack(p.Id,61),"must attack guard");}
  {var m=Game();int enemy=1-m.Active;var bear=Add(m,"MED-229",63,enemy);foreach(int n in Match.Neighbors(63))m.Board[n].Terrain=null;m.Board[61].Owner=enemy;var p=Add(m,"MED-085",60);Do(m,ActionKind.Move,61,p.Id);Check(m.Position(bear.Id)==61,"guard teleport without path");}
  {foreach(var commander in catalog.Cards.Where(c=>c.IsCommander&&c.Playable)){var selected=Enumerable.Repeat(commander.Id,4).ToArray();var m=ContentLoader.CommanderTable(catalog,registry,4,false,91,selected);Check(m.Seats.All(s=>s.Commander==commander&&s.CommanderReady),"demo commander zone "+commander.Id);Check(m.Seats.All(s=>s.main.Concat(s.hand).All(c=>CardFilter.CardColors(c).All(color=>color==6||commander.IdentityColors.Contains(color)))),"demo color identity "+commander.Id);Check(m.Seats.All(s=>s.terrainDeck.Concat(s.piles.SelectMany(p=>p)).All(c=>(c.Color==6||commander.IdentityColors.Contains(c.Color)))),"demo terrain colors "+commander.Id);}}
  {var m=Game();int enemy=1-m.Active;var attack=Add(m,"MED-085",60);var defender=Add(m,"MED-085",61,enemy);var bear=Add(m,"MED-229",64,enemy);m.Board[61].Owner=enemy;Do(m,ActionKind.Attack,61,units:new[]{attack.Id});Check(m.Defense==null&&m.Stack.Last().Rule=="bear-guard","guard before defense assignment");while(m.Stack.Last().Rule=="bear-guard")Do(m,ActionKind.Pass);Check(m.Position(bear.Id)==61&&m.Defense!=null,"guard arrives before combat");}
  {var m=Game();var f=Add(m,"MED-228",60);var seat=m.Seats[m.Active];seat.main.Clear();seat.main.Add(catalog.Get("MED-085"));seat.LastCreatedTerrain=59;Do(m,ActionKind.Activate,unit:f.Id);Settle(m);Check(seat.main.Count==1&&seat.main[0].Id=="MED-085"&&f.Actions==4,"fisher no blue returns revealed card");}
  {var m=Game();var l=Add(m,"MED-226",60);var ally=Add(m,"MED-085",60);var blocker=Add(m,"MED-230",61,1-m.Active);blocker.Modifiers.Add(new Modifier{Attack=10,Defense=10});Do(m,ActionKind.Attack,61,units:new[]{l.Id,ally.Id});Do(m,ActionKind.Defend,blockers:new[]{blocker.Id,blocker.Id});Settle(m);Check(m.Find(l.Id)==null&&m.Find(ally.Id)==null&&m.Seats[l.Owner].DeathCounters==2,"Lissandra observes simultaneous own death");}
  {var m=Game();var seat=m.Seats[m.Active];seat.Commander=catalog.Get("MED-230");Check(m.CommanderMechanicStatus(m.Active).Contains("entrar"),"status absent commander");Add(m,"MED-230",60);Check(m.CommanderMechanicStatus(m.Active).Contains("Lucio + Dazmond"),"status tie");seat.mana[3]=1;Check(m.CommanderMechanicStatus(m.Active).StartsWith("Dazmond"),"status fire");}
  {var m=Game();var v=Add(m,"test-vehicle-cart",60);var a=Add(m,"test-vehicle-scout",60);var b=Add(m,"MED-085",60);var c=Add(m,"MED-085",60);Check(!m.CanMove(v.Id,61),"empty vehicle cannot move");Do(m,ActionKind.BoardVehicle,v.Id,a.Id);Do(m,ActionKind.BoardVehicle,v.Id,b.Id);Check(a.Actions==2&&b.Actions==0&&m.VehicleCapacity(v.Id)==2,"boarding costs 1 PA each");Check(!m.CanBoard(c.Id,v.Id),"normal capacity enforced");var val=Add(m,"MED-231",59);Check(m.VehicleCapacity(v.Id)==3&&m.CanBoard(c.Id,v.Id),"Valeria extra seat");Do(m,ActionKind.BoardVehicle,v.Id,c.Id);Check(m.EffectiveKeywords(v.Id).Contains("flying"),"Valeria inherits keyword");m.Board[61].Terrain=catalog.Get("MED-206");Check(m.CanMove(v.Id,61),"inherited flying bypasses mountain");int pa=a.Actions,mov=a.Movement;Do(m,ActionKind.Move,61,v.Id);Check(m.Position(a.Id)==61&&m.Position(b.Id)==61&&a.Actions==pa&&a.Movement==mov,"vehicle carries without spending passenger resources");Check(!m.CanMove(a.Id,62),"passenger must disembark before walking");Do(m,ActionKind.DisembarkVehicle,unit:a.Id);Check(a.CarrierId<0&&a.Actions==1&&m.Position(a.Id)==61&&!m.EffectiveKeywords(v.Id).Contains("flying"),"disembark same tile loses inherited keyword");m.Deal(v,99);Settle(m);Check(m.Find(b.Id)==null&&m.Find(c.Id)==null&&m.Find(a.Id)!=null,"destroy kills remaining passengers only");}
  {var m=Game();var v=Add(m,"test-vehicle-cart",60);var a=Add(m,"test-vehicle-scout",60);var val=Add(m,"MED-231",59);Do(m,ActionKind.BoardVehicle,v.Id,a.Id);m.Deal(val,99);Settle(m);Check(m.VehicleCapacity(v.Id)==2&&!m.EffectiveKeywords(v.Id).Contains("flying"),"Valeria removal ends aura");Check(a.Card.Keywords.Contains("flying"),"passenger keeps own keywords");}
  {var m=Game();var v=Add(m,"test-vehicle-meka",60);var pilot=Add(m,"MED-197",60);var target=Add(m,"MED-085",61,1-m.Active);Do(m,ActionKind.BoardVehicle,v.Id,pilot.Id);Check(!m.CanAttack(pilot.Id,61)&&!m.CanActivate(pilot.Id)&&m.CanAttack(v.Id,61),"Meka pilot inactive crew enables vehicle");int life=pilot.Health;m.Deal(pilot,1);Check(pilot.Health==life-1,"Meka pilot targetable");Check(m.CanDisembark(pilot.Id),"Meka pilot can exit despite inactive");}
  {var m=Game();var v=Add(m,"test-vehicle-cart",60);var a=Add(m,"test-vehicle-scout",60);Add(m,"MED-085",61,1-m.Active);Do(m,ActionKind.BoardVehicle,v.Id,a.Id);Check(m.CanAttack(a.Id,61),"common vehicle passenger acts");Check(!m.Try(new Command{player=1-m.Active,revision=m.Revision,kind=ActionKind.DisembarkVehicle,unit=a.Id},out _),"unauthorized passenger command rejected");}
  Debug.Log("BICOLOR CHECKS PASSED: "+checks);
 }
}


