using System;
using System.Linq;
using System.Reflection;
using TCG.Foundation;
using TCG.Table;
using UnityEngine;
public static class NewCommanderChecks
{
 static ContentCatalog catalog;static EffectRegistry effects=new EffectRegistry();static int checks,id=120000;
 static void Check(bool x,string name){checks++;if(!x)throw new Exception("NEW COMMANDERS: "+name);}
 static void Do(Match m,ActionKind kind,int target=-1,int unit=-1,string card=null){if(!m.Try(new Command{player=m.Controller,revision=m.Revision,kind=kind,target=target,unit=unit,card=card,pile=0},out var error))throw new Exception("NEW COMMANDERS COMMAND: "+error);}
 static void Invoke(Match m,string name,params object[] args)=>typeof(Match).GetMethod(name,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(m,args);
 static void Settle(Match m){for(int guard=0;guard<150&&(m.Choice!=null||m.Stack.Count>0);guard++){if(m.Choice!=null)Do(m,ActionKind.Choose,m.Choice.Options.First(x=>x.Key!=-1).Key);else if(m.Defense!=null){var d=m.Defense;var b=m.Board[d.Target].Pieces.First(p=>p.Owner==d.Defender);if(!m.Try(new Command{player=m.Controller,revision=m.Revision,kind=ActionKind.Defend,blockers=d.Attackers.Select(_=>b.Id).ToArray()},out var e))throw new Exception(e);}else Do(m,ActionKind.Pass);}Check(m.Choice==null&&m.Stack.Count==0,"settles");}
 static Match Game(){var m=ContentLoader.TestTable(catalog,effects,2,false,22);Do(m,ActionKind.DrawMain);Do(m,ActionKind.Place,Match.Capital(m.Active,2));Do(m,ActionKind.NextPhase);foreach(var cell in m.Board){cell.Terrain=catalog.Get("test-land-0");cell.Owner=m.Active;cell.TerrainOwner=m.Active;}foreach(var s in m.Seats){s.hand.Clear();Array.Clear(s.mana,0,7);}return m;}
 static Piece Add(Match m,string card,int at=60,int owner=-1){var p=new Piece(id++,owner<0?m.Active:owner,catalog.Get(card)){Game=m};m.Board[at].pieces.Add(p);return p;}
 public static void Run()
 {
  checks=0;catalog=ContentLoader.Load(effects);
  for(int n=232;n<=242;n++)Check(catalog.Get("MED-"+n).Playable&&catalog.Get("MED-"+n).IsCommander,"registered "+n);
  {var m=Game();var p=Add(m,"MED-232");m.Seats[p.Owner].mana[0]=2;m.Seats[p.Owner].mana[6]=3;Do(m,ActionKind.Activate,unit:p.Id);Settle(m);Check(p.Attack==8&&p.Defense==8&&p.Actions==1&&m.Seats[p.Owner].Mana.Sum()==0,"absorb entire pool without PA bonus");Invoke(m,"EndModifiers");Check(p.Attack==3&&p.Defense==3,"absorb expires");}
  {var m=Game();var p=Add(m,"MED-233");m.Seats[p.Owner].hand.Add(catalog.Get("MED-085"));p.Actions=0;Invoke(m,"Drain");Settle(m);Check(m.Board.SelectMany(c=>c.Pieces).Count()==2&&m.Seats[p.Owner].HandCount==0,"messenger free summon");m.Seats[p.Owner].hand.Add(catalog.Get("MED-085"));p.Actions=1;p.Actions=0;Invoke(m,"Drain");Check(m.Stack.Count==0&&m.Seats[p.Owner].HandCount==1,"once per turn");}
  {var m=Game();var p=Add(m,"MED-234");var victim=Add(m,"MED-229",61,1-m.Active);m.Seats[p.Owner].grave.Add(catalog.Get("test-mill"));m.DamageTo(victim,1,p);Settle(m);Check(m.Seats[p.Owner].Exile.Any(c=>c.Id=="test-mill")&&!m.Seats[p.Owner].Graveyard.Any(c=>c.Id=="test-mill"),"ancestor free spell then exile");}
  {var m=Game();var p=Add(m,"MED-236");m.Seats[p.Owner].grave.Add(catalog.Get("test-mill"));Do(m,ActionKind.Activate,unit:p.Id);Settle(m);var x=m.ExiledFor(p.Owner).Single();Check(!m.CanCastExiled(x.Id),"exile still requires mana");m.Seats[p.Owner].mana[6]=1;Check(m.CanCastExiled(x.Id),"exile becomes affordable");Do(m,ActionKind.CastExiled,x.Id);Settle(m);Check(m.ExiledFor(p.Owner).Count==0&&m.Seats[p.Owner].grave.Any(c=>c.Id=="test-mill"),"one use and normal destination");}
  {var m=Game();var monk=Add(m,"MED-235");var enemy=Add(m,"MED-229",61,1-m.Active);monk.Modifiers.Add(new Modifier{Defense=10});Do(m,ActionKind.Activate,unit:monk.Id);Settle(m);m.DamageTo(monk,5,enemy);Invoke(m,"Drain");Check(monk.Damage==3&&enemy.Damage==2,"half rounded down and reflected");m.DamageTo(monk,3,enemy);Invoke(m,"Drain");Check(monk.Damage==6&&enemy.Damage==2,"protection consumed once");}
  {var m=Game();var p=Add(m,"MED-237");int life=m.Seats[p.Owner].Life;m.GainLife(p.Owner,4);Settle(m);Check(m.Seats[p.Owner].Life==life+4&&p.Damage==1,"one herald trigger per healing event");}
  {var m=Game();var knight=Add(m,"MED-238");var other=Add(m,"MED-240");var enemy=Add(m,"MED-238",60,1-m.Active);Check(knight.Attack==6&&other.Attack==5&&enemy.Attack==5,"continuous local knight count allied only");m.Board[60].pieces.Remove(other);m.Board[59].pieces.Add(other);Check(knight.Attack==5&&other.Attack==4,"aura updates by tile");}
  {var m=Game();var collector=Add(m,"MED-239");var victim=Add(m,"MED-085",61,1-m.Active);var rune=Add(m,"test-enchantment-blessing",61,victim.Owner);rune.AttachedTo=victim.Id;m.DamageTo(victim,99,collector);Settle(m);var stolen=m.Board.SelectMany(c=>c.Pieces).Single(p=>p.Card.Kind==CardType.Enchantment);Check(stolen.AttachedTo==collector.Id&&stolen.Owner==collector.Owner&&stolen.OriginalOwner==victim.Owner&&collector.Actions==2,"steals attachment and preserves owner");Check(collector.Attack==5&&collector.Defense==5,"enchantment bonus plus collector aura");}
  {var m=Game();Add(m,"MED-240");var equip=catalog.Cards.First(c=>c.Kind==CardType.Equipment&&c.Playable);m.Seats[m.Active].hand.Add(equip);for(int n=0;n<7;n++)m.Seats[m.Active].mana[n]=20;Do(m,ActionKind.Play,60,card:equip.Id);Settle(m);var token=m.Board.SelectMany(c=>c.Pieces).Single(p=>p.Token);Check(token.Card.Attack==3&&m.Board.SelectMany(c=>c.Pieces).Any(p=>p.Card==equip&&p.AttachedTo==token.Id),"chosen beast auto equipped");}
  {var m=Game();var p=Add(m,"MED-241");m.Board[0].Owner=1-m.Active;Do(m,ActionKind.Activate,unit:p.Id);Settle(m);Check(m.Position(p.Id)==0&&p.Actions==0,"infiltration enemy empty terrain");}
  {var m=Game();var thief=Add(m,"MED-242");int enemy=1-m.Active;m.Seats[enemy].main.Clear();m.Seats[enemy].main.Add(catalog.Get("MED-085"));m.MillCards(enemy,1);Invoke(m,"Drain");Settle(m);var x=m.ExiledFor(thief.Owner).Single();Check(x.AnyMana&&x.CardOwner==enemy&&thief.Actions==1,"mill pays converted PA from troops");m.Seats[thief.Owner].mana[6]=2;Do(m,ActionKind.CastExiled,x.Id);Settle(m);var stolen=m.Board.SelectMany(c=>c.Pieces).Single(p=>p.Card.Id=="MED-085");m.Deal(stolen,99);Settle(m);Check(m.Seats[enemy].grave.Contains(stolen.Card),"stolen creature returns to original grave");}
  {var lib=new CollectionLibrary(catalog,new CollectionData());lib.Collect("MED-232");lib.SelectFoil("MED-232",true);lib.SelectStyle("MED-232","standard");var deck=new DeckData();lib.SelectFoil("MED-232",false,deck);lib.SaveDeck(deck);Check(lib.SelectedFoil("MED-232")&&!lib.SelectedFoil("MED-232",deck),"foil independent of style and deck");var copy=deck.Copy();copy.cardLooks[0].foil=true;Check(!deck.cardLooks[0].foil,"foil deep copy");var store=new CollectionStore(System.IO.Path.Combine(System.IO.Path.GetTempPath(),"tcg-foil-"+Guid.NewGuid().ToString("N")));store.Save(lib);var loaded=store.Load(catalog);Check(loaded.SelectedFoil("MED-232")&&!loaded.SelectedFoil("MED-232",loaded.Data.decks[0]),"foil saved and restored");}
  {var filter=new CardFilter{CommandersOnly=true};Check(catalog.Cards.Where(c=>filter.Matches(c,true)).All(c=>c.IsCommander),"commander only filter");}
  {var m=Game();var a=Add(m,"MED-234");var victim=Add(m,"MED-229",61,1-m.Active);m.Seats[a.Owner].grave.Add(catalog.Get("test-mill"));m.DamageTo(victim,1,a);
   for(int n=0;n<30&&!m.Stack.Any(s=>s.Card?.Id=="test-mill"&&s.Rule==null);n++){if(m.Choice!=null)Do(m,ActionKind.Choose,m.Choice.Options.First(x=>x.Key!=-1).Key);else Do(m,ActionKind.Pass);}
   Check(m.Stack.Any(s=>s.Card?.Id=="test-mill"&&s.Rule==null),"ancestor announced replay");m.Seats[m.Priority].hand.Add(catalog.Get("test-counter"));m.Seats[m.Priority].mana[6]=1;Do(m,ActionKind.Play,card:"test-counter");Settle(m);Check(m.Seats[a.Owner].Exile.Any(c=>c.Id=="test-mill"),"countered replay goes to exile");}
  {var m=Game();var a=Add(m,"MED-236");var ally=Add(m,"MED-085",61);var destiny=catalog.Cards.Single(c=>c.Rule=="destiny");m.Seats[a.Owner].grave.Add(destiny);Do(m,ActionKind.Activate,unit:a.Id);Settle(m);for(int n=0;n<7;n++)m.Seats[a.Owner].mana[n]=10;Check(!m.CanCastExiled(m.ExiledFor(a.Owner).Single().Id),"death replacement waits for lethal event");m.Deal(a,99);Invoke(m,"Drain");Settle(m);Check(m.Find(a.Id)!=null&&m.Find(ally.Id)==null&&m.ExiledFor(a.Owner).Count==0,"exiled destiny handles lethal replacement");}
  Debug.Log("NEW COMMANDER CHECKS PASSED: "+checks);
 }
}
