using System;
using System.Linq;
using System.Reflection;
using System.Collections.Generic;
using TCG.Table;
using UnityEngine;
namespace TCG.Foundation.Editor
{
 public static class PreconAuthorChecks
 {
  static int checks,id=990000;static ContentCatalog catalog;static EffectRegistry effects;
  static readonly BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
  static void Check(bool condition,string message){checks++;if(!condition)throw new Exception("PRECON AUTHOR: "+message);}
  static object Call(Match m,string method,params object[] args){try{return typeof(Match).GetMethod(method,Private).Invoke(m,args);}catch(TargetInvocationException e){throw e.InnerException;}}
  static Definition Card(string name,string kind="Creature",int attack=2,int defense=6,string[] traits=null,CardAbility[] abilities=null,int cost=0)=>new Definition(new CardData{id="pca-check-"+name,name=name,kind=kind,attack=attack,defense=defense,actions=1,movement=2,range=1,cost=cost,traits=traits??Array.Empty<string>(),abilities=abilities??Array.Empty<CardAbility>(),subtypes=new[]{"Humano"}},"test");
  static Piece Add(Match m,int owner,int tile,Definition card){var p=new Piece(id++,owner,card){Game=m};m.Board[tile].pieces.Add(p);return p;}
  static Match Game(){var m=ContentLoader.TestTable(catalog,effects,2,false,37);foreach(var cell in m.Board){cell.pieces.Clear();cell.Terrain=catalog.Get("test-land-6");cell.Owner=m.Active;}return m;}
  static void Op(Match m,Pending pending,AbilityOp op,Piece target=null,int player=-1){bool continued=false;Check((bool)Call(m,"ResolvePreconAuthorOp",pending,new CardAbility(),target,op,player<0?pending.Owner:player,(Action)(()=>continued=true)),"op handled "+op.kind);m.ResolveInitialEffects();if(m.Choice==null)Check(continued,"op continuation "+op.kind);}
  static void Choose(Match m,int key){Check(m.Try(new Command{kind=ActionKind.Choose,player=m.Controller,revision=m.Revision,target=key},out var error),"choice "+error);}
  public static void Run()
  {
   checks=0;effects=new EffectRegistry();catalog=ContentLoader.Load(effects);
   Check(catalog.Cards.Count(c=>c.Id.StartsWith("AUTOR-20261007-",StringComparison.Ordinal))==14,"fourteen authored definitions retained");foreach(var card in catalog.Cards.Where(c=>c.Id.StartsWith("AUTOR-20261007-",StringComparison.Ordinal)))Check(card.Playable&&AbilitySchema.Valid(card.Abilities.ToArray()),"author data executable "+card.Id);
   {var m=Game();int owner=m.Active,victim=1-owner;Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-look-player"},player:victim);Check(m.Choice!=null&&m.Choice.Owner==owner&&m.Choice.Prompt.Contains(m.Seats[victim].main.Last().Name),"peek belongs to activator only");Choose(m,0);}
   {var m=Game();int owner=m.Active;var trigger=new CardAbility{trigger="pca-near-terrain",ops=new[]{new AbilityOp{kind="pca-mill-enemies",a=1}}};var crab=Add(m,owner,60,Card("crab",abilities:new[]{trigger}));Call(m,"PreconAuthorTerrainPlaced",owner,61);Check(m.Stack.Any(p=>p.Card==crab.Card),"orthogonal terrain queues crab");var stack=(List<Pending>)typeof(Match).GetField("stack",Private).GetValue(m);stack.Clear();Call(m,"PreconAuthorTerrainPlaced",owner,60);Check(m.Stack.Count==0,"same tile is not adjacent");}
   {var m=Game();int owner=m.Active;var old=Add(m,owner,60,Card("old"));var replacement=Add(m,owner,62,Card("replacement"));old.Damage=2;replacement.Damage=1;var equipment=Add(m,owner,60,Card("equipment","Equipment"));equipment.AttachedTo=old.Id;var battle=new Pending{Owner=owner,Attackers=new[]{old.Id},Target=61};((List<Pending>)typeof(Match).GetField("stack",Private).GetValue(m)).Add(battle);Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-swap-combat"},old);Choose(m,replacement.Id);Check(m.Position(old.Id)==62&&m.Position(replacement.Id)==60&&m.Position(equipment.Id)==62&&battle.Attackers.Single()==replacement.Id,"swap positions attached equipment and combat identity");Check(old.Damage==2&&replacement.Damage==1,"swap keeps individual damage");}
   {var m=Game();int owner=m.Active;Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-mark-tile"});Choose(m,61);int hand=m.Seats[owner].HandCount;Call(m,"PreconAuthorTerrainPlaced",1-owner,61);Check(m.Seats[owner].HandCount==hand,"foreign terrain does not satisfy mark");Call(m,"PreconAuthorTerrainPlaced",owner,61);Check(m.Seats[owner].HandCount==hand+2,"own placed terrain draws two");Call(m,"PreconAuthorTerrainPlaced",owner,61);Check(m.Seats[owner].HandCount==hand+2,"mark pays once");}
   {var m=Game();int owner=m.Active;var center=Add(m,1-owner,60,Card("center"));var pushed=Add(m,1-owner,61,Card("pushed"));m.Board[63].Terrain=null;Call(m,"PreconWave",owner,60,new Pending{Owner=owner});Check(center.Damage==3&&m.Position(pushed.Id)==62,"wave deals three and stops before hole");}
   {var m=Game();int owner=m.Active;var jonas=Add(m,owner,60,Card("jonas",traits:new[]{"pca-jonas"}));m.Seats[owner].grave.Add(Card("small",cost:3));m.Seats[1-owner].grave.Add(Card("large",cost:5));Check((int)Call(m,"PreconAuthorBonus",jonas,3)==7,"Jonas sums maximum creature mana costs minus base PA");Op(m,new Pending{Owner=owner,Source=jonas,SourceCell=60},new AbilityOp{kind="pca-block-tile"});Choose(m,61);Check((bool)Call(m,"PreconAuthorMoveBlocked",jonas,61),"Jonas tile blocks movement");}
   {var m=Game();int owner=m.Active,victim=1-owner;var dead=Card("grave-exile");m.Seats[victim].grave.Add(dead);int main=m.Seats[victim].MainCount;Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-exile-grave-mill",a=2});Choose(m,0);Check(m.Seats[victim].Exile.Contains(dead)&&m.Seats[victim].MainCount==main-2,"Ciri exiles creature and mills cemetery owner");}
   {var m=Game();int owner=m.Active;var host=Add(m,owner,60,Card("doc-host"));var document=Add(m,owner,60,Card("document","Equipment",traits:new[]{"pca-document"}));document.AttachedTo=host.Id;Call(m,"PreconAuthorTurn");int a=(int)Call(m,"PreconAuthorBonus",host,0),d=(int)Call(m,"PreconAuthorBonus",host,1);Check(a==2&&d==0||a==0&&d==6,"document samples one attribute at controller start");Call(m,"PreconAuthorTurn");a=(int)Call(m,"PreconAuthorBonus",host,0);d=(int)Call(m,"PreconAuthorBonus",host,1);Check(a==2&&d==0||a==0&&d==6,"document does not compound its previous roll");}
   {var m=Game();int owner=m.Active;var factory=Add(m,owner,60,Card("factory","Construction",traits:new[]{"pca-factory"}));Call(m,"PreconAuthorEntered",factory);var dead=Add(m,1-owner,61,Card("factory-victim"));Call(m,"CommitKill",dead,-1);Op(m,new Pending{Owner=owner,Source=factory,SourceCell=60},new AbilityOp{kind="pca-horror"});Choose(m,1-owner);var horror=m.Board[60].Pieces.Single(p=>p.Token);Check(horror.Card.Attack==1&&horror.Card.Defense==1&&horror.Card.Actions==1&&horror.Card.Movement==2,"factory counts enemy death and explicit horror profile");}
   {var m=Game();int owner=m.Active;var dead=Card("exumar");m.Seats[owner].grave.Add(dead);int hand=m.Seats[owner].HandCount;Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-exumar"});Choose(m,0);Check(m.Seats[owner].Exile.Contains(dead)&&m.Seats[owner].HandCount==hand+1,"exumar exiles and draws");}
   {var m=Game();int owner=m.Active;var own=Add(m,owner,60,Card("symphony-own"));var enemy=Add(m,1-owner,60,Card("symphony-enemy"));Add(m,owner,60,Card("symphony","Enchantment",traits:new[]{"pca-tile-enchantment"}));m.Seats[owner].grave.Add(Card("one"));m.Seats[1-owner].grave.Add(Card("two"));m.Seats[1-owner].grave.Add(Card("three"));Check((int)Call(m,"PreconAuthorBonus",own,0)==-1&&(int)Call(m,"PreconAuthorBonus",enemy,1)==-2,"symphony uses each creature controller cemetery");Check((bool)Call(m,"PreconAuthorEnchantmentPlacement",m.Board[60].Pieces.Last().Card,owner,60,-1),"tile enchantment takes no host");}
   {var m=Game();int owner=m.Active;var enemy=Add(m,1-owner,60,Card("persuade"));m.Board[60].Owner=1-owner;m.Board[59].Owner=owner;Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-persuade"},enemy);Check(enemy.Owner==owner&&enemy.OriginalOwner==1-owner&&m.Position(enemy.Id)==59,"persuasion keeps original owner and moves nearest realm");}
   {var m=Game();int owner=m.Active;var dead=Card("realm-creature");m.Seats[owner].grave.Add(dead);Op(m,new Pending{Owner=owner,SourceCell=60},new AbilityOp{kind="pca-realm-return"});Choose(m,0);Check(m.Board[60].Pieces.Count==1,"realm returns chosen defender");Call(m,"PreconAuthorEndTurn");Check(m.Board[60].Pieces.Count==0&&m.Seats[owner].Graveyard.Contains(dead),"realm defender returns to grave at end");}
   {var m=Game();int owner=m.Active,victim=1-owner;var source=Add(m,owner,60,Card("mill-damage"));var target=Add(m,victim,61,Card("damage-victim"));Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-mill-damage"},source);int main=m.Seats[victim].MainCount;Call(m,"PreconAuthorCombatDamage",source,target,3);Check(m.Seats[victim].MainCount==main-3,"R008 mills actual creature damage");Op(m,new Pending{Owner=owner,Amount=8},new AbilityOp{kind="pca-sacrifice-mill"},player:victim);Check(m.Seats[victim].MainCount==main-11,"R012 uses sacrificed stat snapshot");}
   {var m=Game();int owner=m.Active,enemy=1-owner;var card=m.Seats[enemy].main.Last();Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-secret-exile"});Choose(m,enemy);Check(m.Choice.Owner==owner&&m.Choice.Prompt.Contains(card.Name),"secret top inspected only by activator");Choose(m,1);Check(m.ExiledFor(owner).Any(p=>p.Card==card&&p.AnyMana)&&!(bool)Call(m,"PreconAuthorExileVisible",card,enemy)&&(bool)Call(m,"PreconAuthorExileVisible",card,owner),"secret exile permission and hidden enemy face");Call(m,"PreconAuthorRevealExile",card);Check((bool)Call(m,"PreconAuthorExileVisible",card,enemy),"casting may reveal exiled card");}
   {var m=Game();int owner=m.Active,enemy=1-owner;var trigger=new CardAbility{trigger="pca-killed",ops=new[]{new AbilityOp{kind="pca-mill-killer",a=5}}};var source=Add(m,owner,60,Card("killer-trigger",abilities:new[]{trigger}));Call(m,"CommitKill",source,enemy);Check(m.Stack.Any(p=>p.Card==source.Card&&p.Target==enemy),"death effect preserves killer owner");int main=m.Seats[enemy].MainCount;Op(m,new Pending{Owner=owner,Target=enemy},new AbilityOp{kind="pca-mill-killer",a=5});Check(m.Seats[enemy].MainCount==main-5,"killer owner mills five");}
   {var m=Game();int owner=m.Active;var top=m.Seats[owner].main.Last();int count=m.Seats[owner].MainCount;Op(m,new Pending{Owner=owner},new AbilityOp{kind="pca-top-keep-mill",a=5});Choose(m,0);Check(m.Seats[owner].main.Last()==top&&m.Seats[owner].MainCount==count-4&&m.Seats[owner].grave.Milled.Count()==4,"keep selected top and mill four with provenance");}
   {var m=Game();int owner=m.Active;var source=Card("excluded-source");var other=Card("other-grave");m.Seats[owner].grave.Add(source);m.Seats[owner].grave.Add(other);Op(m,new Pending{Owner=owner,Card=source},new AbilityOp{kind="pca-grave-other",a=2});Check(m.Choice.Options.Count(o=>o.Key>=0)==1&&m.Choice.Options.Any(o=>o.Key==-1),"recover excludes source and allows fewer than two");Choose(m,0);Check(m.Seats[owner].hand.Contains(other)&&m.Seats[owner].Graveyard.Contains(source),"source remains excluded from recovery");}
   {var m=Game();int owner=m.Active,enemy=1-owner;var trigger=new CardAbility{trigger="pca-own-other-death",once=true,ops=new[]{new AbilityOp{kind="pca-catacombs-return"}}};var source=Add(m,owner,60,Card("catacombs-source",abilities:new[]{trigger}));var cheap=Card("catacombs-cost-two",cost:2);var expensive=Card("catacombs-too-expensive",cost:3);var foreign=Card("catacombs-not-own",cost:1);m.Seats[owner].grave.Add(cheap);m.Seats[owner].grave.Add(expensive);m.Seats[enemy].grave.Add(foreign);var dead=Add(m,owner,61,Card("catacombs-dead",cost:1));Call(m,"CommitKill",dead,-1);var pending=m.Stack.Single(p=>p.Card==source.Card);Check(pending.Subject==dead,"catacombs trigger preserves other dead creature");var second=Add(m,owner,61,Card("catacombs-second",cost:3));Call(m,"CommitKill",second,-1);Check(m.Stack.Count(p=>p.Card==source.Card)==1,"catacombs once per turn");int life=m.Seats[owner].Life;((Dictionary<Definition,int>)typeof(Match).GetField("foreignOwners",Private).GetValue(m))[cheap]=enemy;Op(m,pending,new AbilityOp{kind="pca-catacombs-return"});Check(m.Choice!=null&&m.Choice.Options.Count(o=>o.Key>=0)==1&&m.Choice.Options.Any(o=>o.Key==-1),"catacombs allows only different own creature cost<=2 and optional refusal");Choose(m,0);var resurrected=m.Board[60].Pieces.Single(p=>p.Card==cheap);Check(resurrected.Owner==owner&&resurrected.OriginalOwner==enemy&&m.Seats[owner].Life==life-2,"catacombs returns exactly on source tile, pays two and preserves original owner");}
   {var m=Game();int owner=m.Active,enemy=1-owner;var trigger=new CardAbility{trigger="pca-own-other-death",once=true,ops=new[]{new AbilityOp{kind="pca-catacombs-return"}}};var source=Add(m,owner,60,Card("catacombs-enemy-gate",abilities:new[]{trigger}));var enemyDead=Add(m,enemy,61,Card("catacombs-enemy-dead"));Call(m,"CommitKill",enemyDead,-1);Check(!m.Stack.Any(p=>p.Card==source.Card),"enemy death never triggers catacombs");m.Seats[owner].grave.Add(Card("catacombs-spare",cost:1));int life=m.Seats[owner].Life;Call(m,"CommitKill",source,-1);Check(!m.Stack.Any(p=>p.Card==source.Card),"source's own death never triggers itself");Op(m,new Pending{Owner=owner,Source=source,SourceCell=60,Subject=enemyDead},new AbilityOp{kind="pca-catacombs-return"});Check(m.Choice==null&&m.Seats[owner].Life==life,"missing source cannot pay or reanimate elsewhere");}
   {var m=Game();int owner=m.Active;bool continued=false;Check(!(bool)Call(m,"ResolvePreconAuthorOp",new Pending{Owner=owner},new CardAbility(),null,new AbilityOp{kind="foreign-op"},owner,(Action)(()=>continued=true))&&!continued,"foreign operation falls through");}
   Debug.Log("PRECON AUTHOR CHECKS PASSED: "+checks);
  }
 }
}
